### PR TITLE
Add Models for About Us, Hero, Footer, and Navbar Components of Landing Page

### PR DESCRIPTION
**Pull request by jayll0**
Description:
This pull request introduces the models for the About Us, Hero, Footer, and Navbar components, including both request and response structures. These models will be used to handle the creation, updating, and retrieval of component data within our application.

Changes:

Added land_aboutus_request and land_aboutus_response structs to represent the About Us component.
Added land_hero_request and land_hero_response structs to represent the Hero component.
Added land_footer_request and land_footer_response structs to represent the Footer component.
Added land_navbar_request and land_navbar_response structs to represent the Navbar component.
Files Added:

models/land_aboutus.go
models/land_hero.go
models/land_footer.go
models/land_navbar.go
Testing:

Verified that all struct definitions match the required fields.
Ensured proper JSON tags for serialization and deserialization.
Reviewers:
Please review the struct definitions and ensure that all required fields are included and correctly typed. Any feedback on improving the naming conventions or additional fields that might be necessary is welcome.

### CODE REVIEW

**Review by krisnaganesha1609 — CHANGES_REQUESTED** [review]
Need Attention: 
- Sebelum json:"nama_kolom", tambahin juga gorm:"column:nama_kolom"
Tambahan tersebut berlaku di semua models*

**Comment by jayll0** [comment]
kemarin bilang gak pakai gorm :)

**Comment by jayll0** [comment]
ini fork ulang apa edit disitu gorm nya

**Review by krisnaganesha1609 — APPROVED** [review]
NICE!

**Pull request merged**
